### ISSUE TITLE
Agent create only client and participant  

### ISSUE THREAD

**Issue by biontix** [micro-ROS/micro-ROS-Agent#102]
Hello everyone! I am using microros in xilinx ultra96 with freeRTOS where I run the client. Microros Agent is running on the Host PC and the communication client/agent is via serial. I am trying to run simple demo int32_publisher found in micro-ROS-demos.

When I run the agent with `ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/ttyUSB1 -v 6` I can see in the log that the session is established, it create client and partecipant and than stopped to create other entities. In the client side I use my own custom transport, with xilinx serial API uartps.h. The problem could be in the read Operation?

The agent Output: 

![log](https://user-images.githubusercontent.com/41077457/135708126-bc05771f-e1e6-4d8d-9c8a-7f5711a4a7bb.png)

My read and write operation: 

![customtransp](https://user-images.githubusercontent.com/41077457/135707711-f4157c6b-b163-454f-adb3-0d321675c6fe.png)

**Comment by biontix** [comment]
Problem fixed: XUartPs_Send is non-blocking function, so sometimes happened while the UART was sending, XUartPs_Recv was call causing bytes loss. We need to wait until UART finish sending

**Comment by sapertuz** [comment]
Hello @crivi30 

How were you able to embed MicroRos on the ZynqMP? 
Do you have any resources you can share on how to achieve this?
