### ISSUE TITLE
ssize_t not declared in this scope

### ISSUE THREAD

**Issue by rosterloh** [micro-ROS/micro-ROS-Agent#122]
**Describe the bug**
When trying to build micro-ROS-Agent in a ROS 2 source workspace on a Raspberry Pi I get the following errors.
```
In file included from /home/pi/ros2_galactic/build/micro_ros_agent/agent/src/xrceagent/src/cpp/transport/stream_framing/StreamFramingProtocol.cpp:15:
/home/pi/ros2_galactic/build/micro_ros_agent/agent/src/xrceagent/include/uxr/agent/transport/stream_framing/StreamFramingProtocol.hpp:98:41: error: ‘ssize_t’ was not declared in this scope; did you mean ‘size_t’?
   98 |     using WriteCallback = std::function<ssize_t (
      |                                         ^~~~~~~
      |                                         size_t
```
**To Reproduce**
Steps to reproduce the behaviour:
1. Setup build environment as [here](https://docs.ros.org/en/galactic/Installation/Ubuntu-Development-Setup.html) 
2. git clone https://github.com/micro-ROS/micro_ros_msgs.git -b galactic src/uros/micro_ros_msgs
3. git clone https://github.com/micro-ROS/micro-ROS-Agent.git -b galactic src/uros/micro_ros_agent
4. colcon build --install-base /opt/ros/galactic --merge-install --packages-up-to micro_ros_agent --cmake-args "-DUAGENT_BUILD_EXECUTABLE=OFF -DUAGENT_P2P_PROFILE=OFF --no-warn-unused-cli"

**Expected behaviour**
A successful build.

**System information:**
 - OS: Debian Bullseye 64 bit
 - ROS 2 Galactic
 - Version galactic

**Comment by rosterloh** [comment]
![Screenshot from 2022-03-01 12-41-20](https://user-images.githubusercontent.com/1049569/156171682-3036e205-0398-4231-a174-687a51507b46.png)

**Comment by rosterloh** [comment]
I think this is related to https://github.com/eProsima/Micro-XRCE-DDS-Agent/pull/297. SuperBuild is using ros2 branch and this fix is in develop

**Comment by rosterloh** [comment]
Confirmed working when changing https://github.com/micro-ROS/micro-ROS-Agent/blob/galactic/micro_ros_agent/cmake/SuperBuild.cmake#L29 to `develop`

**Comment by AntumArk** [comment]
Are you running on RPI3b+ or 4?

**Comment by rosterloh** [comment]
@AntumArk on a CM 4

**Comment by Acuadros95** [comment]
Just updated `ros2` branch with develop changes, should fix this problem.

**Comment by pablogs9** [comment]
Please confirm the fix and we will close

**Comment by rosterloh** [comment]
This will definitely fix it. Happy to close
