### ISSUE TITLE
Repeated creation of publishers causes memory usage to grow

### ISSUE THREAD

**Issue by laogui-wind** [micro-ROS/micro-ROS-Agent#144]
## Issue template

- Hardware description: RK3399 runing unbutu 20.04
- RTOS: RK3399
- Installation type: source code compilation
- Version or commit hash: foxy

#### Steps to reproduce the issue
Just run the following line of statements in a loop to reproduce:
`ros2 topic pub --once <topic forwarded by agent> <msg-type> <msg-data>`

#### Actual behavior
Using htop to continuously observe, the memory usage grows slowly

**Comment by pablogs9** [comment]
Does this happen if you do not use the micro-ROS Agent? If you subscribe using `ros2 topic echo ...`?

**Comment by laogui-wind** [comment]
Sorry, I didn't describe the problem exactly. The actual situation is that the memory usage of the application `micros_ros_agent` is increasing.

**Comment by pablogs9** [comment]
Which version of the micro-ROS agent are you using?

**Comment by laogui-wind** [comment]
OK,thank you!

**Comment by laogui-wind** [comment]
After updating to the latest version, we found that micro_ros_agent still had memory growth.

**Comment by laogui-wind** [comment]
**Steps to reproduce the issue**
We reproduce this phenomenon based on a routine: https: //micro.ros.org/docs/tutorials/core/first_application_linux/
In the first terminal, we create an agent:
```bash
ros2 run micro_ros_agent micro_ros_agent udp4 --port 8888
```
In Terminal 2, create a subscriber named /microROS/ping:
```bash
ros2 topic echo /microROS/ping std_msgs/msg/Header
```
In Terminal 3, run the following script to loop through the creation of publishers:
```bash
#!/bin/bash

source /opt/ros/foxy/setup.bash

while true
do
	ros2 topic pub --once /microROS/ping std_msgs/msg/Header "{'frame_id' : '1'}"
done
```
**Actual behavior**
By observing the agent through htop, it can be found that the value of RES is increasing:
![Screenshot from 2022-06-07 00-04-26](https://user-images.githubusercontent.com/54614784/172275541-1c7d86ac-46f7-416e-b5b8-aa5c4ebe0d7a.png)
![2](https://user-images.githubusercontent.com/54614784/172275677-15bf940d-6c80-4e46-8dd2-d6bb4162439b.png)
![3](https://user-images.githubusercontent.com/54614784/172275692-a51d2675-6d9f-4782-9cf2-b58787642eb8.png)
![4](https://user-images.githubusercontent.com/54614784/172275701-eec66af0-bb85-4605-bfa2-982fb2b41683.png)

**Comment by pablogs9** [comment]
I have replicated your whole environment in micro-ROS Humble and it does not seem to increase the RES memory. Could you make a test in the newest release?

**Comment by laogui-wind** [comment]
My test is based on the foxy branch and the commit id is 4dd8ffe63bee1e9d1e0400d734706d0be9c775ad.
What is the id of the latest release you are talking about?
In addition, the above test may take one to two hours to have obvious symptoms.

**Comment by pablogs9** [comment]
I'm talking about [v3.0.2/Humble](https://github.com/micro-ROS/micro-ROS-Agent/releases/tag/3.0.2), I'll take into account the time considerations in my next test

**Comment by laogui-wind** [comment]
OK, thanks for your suggestion.

**Comment by laogui-wind** [comment]
We will have many difficulties in changing the ros version. So, is there any commit on the humble branch that can be merged into the foxy branch to solve this problem?

**Comment by pablogs9** [comment]
I have tested the environment with micro-ROS Agent and I have been able to replicate your scenario. Also, I have replicated the environment using a standalone Micro XRCE-DDS Agent and there is no memory leak there. I we can infer that there is a memory leak in some part of the micro-ROS Agent, probably in the graph manager due to the nature of the scenario (that creates a new participant for each topic pub).

I will investigate more tomorrow.

**Comment by pablogs9** [comment]
Hello @laogui-wind could you check this patch: https://github.com/micro-ROS/micro-ROS-Agent/pull/147 ?

**Comment by laogui-wind** [comment]
Ok, we're testing the latest commit, thanks again for your help.

**Comment by pablogs9** [comment]
Please report so we can close this issue

**Comment by laogui-wind** [comment]
After a period of testing, there is no memory leak. I think the problem has been solved, thanks for your help.
