### ISSUE TITLE
Humble snap

### ISSUE THREAD

**Issue by Guillaumebeuzeboc** [micro-ROS/micro-ROS-Agent#163]
For now, the `Foxy` micro-ros-agent snap is the only one published and is published on the `latest` [track](https://snapcraft.io/docs/channels#heading--tracks).

Right now, [the snap is released](https://github.com/micro-ROS/micro-ROS-Agent/blob/foxy/.github/workflows/snap.yaml#L50) on the store under different `Risk` (candidate and edge). But could also be released under different `Tracks` (`lastest`, `foxy`, and `humble`). Developers must currently make a request for `tracks` to be added to their snap via the [#store-requests](https://forum.snapcraft.io/c/store-requests) forum category.

Switching from one track to another could be done this way:
`sudo snap refresh micro-ros-agent --channel=humble/stable`

A good example of what a mutli-track snap looks like is the [snapcraft snap](https://snapcraft.io/snapcraft):
![image](https://user-images.githubusercontent.com/8058486/183862863-9db235a3-c63d-45bb-9a5b-5620d26b0006.png)

Snapcraft recent release (7.1.1) brings along core22 support for ROS 2 Humble snaps. So, porting the current Foxy snap to Humble should not require so much work.

I can help on modifying the `snapcraft.yaml` to build the Humble snap and the CI to automatically build and publish the Humble snap (while keeping the Foxy snap).
What do you think? Would you be interested in requiring tracks to release multiple version of the micro-ros-agent?

**Comment by pablogs9** [comment]
Lates micro-ROS Agent is distributed via Vulcanexus: https://docs.vulcanexus.org/en/latest/rst/installation/linux_binary_installation.html
