### ISSUE TITLE
Agent crashes with Not enough memory in the buffer stream

### ISSUE THREAD

**Issue by chrisjaxy** [micro-ROS/micro-ROS-Agent#173]
**Describe the bug**
The agent crashes when I send a small amount of incorrect data to the agent port.

**To Reproduce**
Steps to reproduce the behaviour:
1. ros2 run micro_ros_agent micro_ros_agent udp4 --port 8888
2. echo "1" > /dev/udp/10.211.55.3/8888

**Expected behaviour**
The agent is running normally.

**System information (please complete the following information):**
 - OS: Ubuntu 20.04
 - ROS 2 Foxy
 - Version lastest

**Additional context**
![image](https://user-images.githubusercontent.com/95396234/187585261-d711997b-3360-476a-aca4-b6d93ea3e573.png)

**Comment by chrisjaxy** [comment]
I tested on humble and found the same problem.

**Comment by pablogs9** [comment]
Working on it

**Comment by pablogs9** [comment]
Working on it here: https://github.com/eProsima/Micro-XRCE-DDS-Agent/pull/314

**Comment by chrisjaxy** [comment]
I did a simple test and the problem didn't happen again.
