### ISSUE TITLE
Using simulation time for synchronization

### ISSUE THREAD

**Issue by dsix-ls2n** [micro-ROS/micro-ROS-Agent#177]
- Test with PX4 autopilot SITL and microDDS Client
- Version or commit hash: humble branch, last commit

In the current state of the micro-ROS-Agent, I didn't see the possibility to synchronize with the client using the ROS simulation time. As it is a usefull feature for an SITL simulation, is it possible anyway? Or can it be implemented as a future feature?

**Comment by pablogs9** [comment]
This is not a planned feature. We are open to contributions via Pull Request in any micro-ROS repo or contact support@eProsima.com if commercial support is required.
