### ISSUE TITLE
build agent without filling up memory for 1GB of RAM

### ISSUE THREAD

**Issue by AhmadSameh** [micro-ROS/micro-ROS-Agent#180]
Hardware: Raspberry pi 3
Os: Ubuntu 22.04 server
Ros-distro: humble
Memory: 1GB

Hello,
I can't build the agent for my raspberry pi 3 due to the small memory, the building process always crashes. Is it even possible to build it for the raspberry pi 3? If yes, what are the steps to do so.

**Comment by Acuadros95** [comment]
Hi @AhmadSameh,

What process are you following to install the agent?
