### ISSUE TITLE
micro_ros_agent not found when starting sensor_combined_listener.launch.py

### ISSUE THREAD

**Issue by marcusnorgren** [micro-ROS/micro-ROS-Agent#181]
See https://github.com/micro-ROS/micro_ros_setup/issues/609#issue-1566294399

I link this here to avoid creating duplicates, but it seems perhaps more relevant for this repo.

**Comment by pablogs9** [comment]
Duplicated https://github.com/micro-ROS/micro_ros_setup/issues/609
