### ISSUE TITLE
Parameters not working in Iron through cli

### ISSUE THREAD

**Issue by rosterloh** [micro-ROS/micro-ROS-Agent#195]
**Describe the bug**
Using get|set|dump from the ros2 cli fails with `Wait for service timed out waiting for parameter services for node /micro_ros_node`. If you attempt to get or set parameters in code this works successfully.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create micro-ROS application with parameter server like [this](https://github.com/micro-ROS/micro_ros_espidf_component/blob/main/examples/parameters/main/main.c)
2. Connect the agent
3. Run `ros2 param dump esp32_param_node`
4. See error `Wait for service timed out waiting for parameter services for node /esp32_param_node`

**Expected behaviour**
ros2 param cli commands work as expected the same as non micro-ROS nodes

**System information (please complete the following information):**
 - OS: Ubuntu 22.04
 - ROS 2 Iron
 - Version 4.0.3

**Comment by pablogs9** [comment]
Hey @rosterloh, we are currently releasing and testing Iron for micro-ROS, the official release is not already out. 

CC: @Acuadros95 PTAL

**Comment by rosterloh** [comment]
@pablogs9 I completely understand. I just saw you were working on it so I thought I'd bring it up while you were busy. I'd happily help test or work on anything for you if it helps.

**Comment by Acuadros95** [comment]
We were missing a parameter service on the micro-ROS client side, that is the reason for the `Wait for service timed out waiting for parameter services` message.

@rosterloh Thanks for checking this! This PR will solve the issue: https://github.com/ros2/rclc/pull/354

**Comment by rosterloh** [comment]
Amazing thanks @Acuadros95!

**Comment by Acuadros95** [comment]
Closing as https://github.com/ros2/rclc/pull/354 is merged!
