### ISSUE TITLE
Missing debian release for micro-ros-agent

### ISSUE THREAD

**Issue by pulak-gautam** [micro-ROS/micro-ROS-Agent#222]
## Issue template

- Installation type: debian
- Version or commit hash: humble

#### Additional information

I was wondering why ``micro_ros_agent`` release repository was archived. This hinders us to make Debian releases of the packages  which have dependency on ``micro_ros_agent``. Could you please clarify what steps we could take to circumvent around this?
Thank you

**Comment by pablogs9** [comment]
`micro_ros_agent` is released as a Debian package in Vulcanexus: https://docs.vulcanexus.org/en/latest/rst/installation/linux_binary_installation.html

**Comment by pulak-gautam** [comment]
Thank you. Will check out the same and will let you know if I face any hiccups.
