### ISSUE TITLE
Repo cleaning

### ISSUE THREAD

**Issue by julionce** [micro-ROS/micro-ROS-Agent#25]
The following is a list of suggested actions to clean-up this repo:

- [ ] remove branches: [master], [develop], [6lowpan] and [Crystal],
- [ ] clore #17. 

[master]: https://github.com/micro-ROS/micro-ROS-Agent/tree/master
[develop]: https://github.com/micro-ROS/micro-ROS-Agent/tree/develop
[6lowpan]: https://github.com/micro-ROS/micro-ROS-Agent/tree/feature/6lowpan
[Crystal]: https://github.com/micro-ROS/micro-ROS-Agent/tree/Crystal

**Comment by ralph-lange** [comment]
No comment from my side as I was never involved in this repo.

**Comment by iluetkeb** [comment]
Same for me.
