### ISSUE TITLE
Micro-ROS Agent Communication Port issue - foxy

### ISSUE THREAD

**Issue by thihakyawjob** [micro-ROS/micro-ROS-Agent#33]
Hi,

micro_ros_agent system has problem in foxy release. It always ask SUBCOMMAND.

> root@1aa2455843cc:/uros_ws# ros2 run micro_ros_agent micro_ros_agent udp 9999
> A subcommand is required
> Run with --help for more information.
> 
> Enter command: --help
> micro-ROS Agent
> Usage: [OPTIONS] SUBCOMMAND
> 
> Options:
> -h,--help Print this help message and exit
> 
> Subcommands:
> udp4 Launch a UDP/IPv4 server
> udp6 Launch a UDP/IPv6 server
> tcp4 Launch a TCP/IPv4 server
> tcp6 Launch a TCP/IPv6 server
> serial Launch a Termios server
> pseudoterminal Launch a pseudoterminal server
> q Exit
> 
> Enter command:
> 

Please advise me how to fix the issue.

Thanks.
Regards,
Thiha Kyaw

**Comment by RobertWilbrandt** [comment]
It seems to me you have a wrong understanding understanding of the cli. Could you try either

```console
ros2 run micro_ros_agent micro_ros_agent udp4 --port 9999
```
or
```console
ros2 run micro_ros_agent micro_ros_agent udp6 --port 9999
```
(depending on your network setup)? This at least starts the agent for me and is consistent to the tutorials. But agreed, this is an unintuitive cli response.
