### ISSUE TITLE
Multiserial agent parsing arguments incorrectly in docker image

### ISSUE THREAD

**Issue by ruimscarvalho98** [micro-ROS/micro-ROS-Agent#70]
## Issue template

- Hardware description: 2x Crazyflie 2.1
- RTOS: freeRTOS
- Installation type: Docker (not working) and micro-ros-setup (working)
- Version or commit hash: foxy

#### Steps to reproduce the issue
I am running the multiserial agent both in the docker container and using the micro-ros-setup helper scripts.
For the docker container I simply run:
```
sudo docker run -it --rm -v /dev:/dev --privileged --net=host microros/micro-ros-agent:foxy multiserial --devs "/dev/ttyS10 /dev/ttyS20"  -v6
```
Using the micro-ros-setup i run (as root to have permission to read/write in /dev)  after building the agent and sourcing the workspace:
```
ros2 run micro_ros_agent micro_ros_agent multiserial --devs "/dev/ttyS10 /dev/ttyS20" -v6
```
#### Expected behavior
The expected behaviour is the one i get in the micro-ros-setup building process where I receive data from *both* serial devices:
![non-docker](https://user-images.githubusercontent.com/25509410/123415953-e00dee80-d5ad-11eb-9645-845378689758.png)

#### Actual behavior
Inside docker I only read data from one serial device - the first one to be precise, which leads me to think maybe the parsing is not working with docker. I've tried running both (without the bridges) and as you can see in the screenshot bellow the docker one only looks for the first serial port altough the command is the same:
![comparison](https://user-images.githubusercontent.com/25509410/123416493-8823b780-d5ae-11eb-9320-39f996bbcc14.png)

#### Additional information
For connecting the crazyflies I am running two separate bridges with two radios and two separate socat connections: /dev/ttyS10 <-> /dev/ttyS11 and  /dev/ttyS20 <-> /dev/ttyS21
Btw i am running the crazyflie_position_publisher app and can confirm it works with multiserial

**Comment by pablogs9** [comment]
@Acuadros95 can you check this?

**Comment by ruimscarvalho98** [comment]
Hey again! After fiddling around with this a bit more, I found that the problem can be solved by replacing the line:

`exec ros2 run micro_ros_agent micro_ros_agent $@`

In the dockerfile's entrypoint script with:

`exec ros2 run micro_ros_agent micro_ros_agent "$@"`

more info about this can be seen [here](https://www.gnu.org/software/bash/manual/html_node/Special-Parameters.html).

It's an extremely simple change but if you want me to open a PR for it let me know

Another option, would be to replace the parsing method to not use a string such as `multiserial --devs /dev/ttyXX /dev/ttyYY /dev/ttyZZ` which might be a bit cleaner and more intuitive imo.

**Comment by pablogs9** [comment]
Can you open the PR please?

**Comment by ruimscarvalho98** [comment]
Done

**Comment by pablogs9** [comment]
https://github.com/micro-ROS/docker/pull/62 merged, closing
