### ISSUE TITLE
port dosen't appear with snap interface

### ISSUE THREAD

**Issue by MuhammadAlhaddad** [micro-ROS/micro-ROS-Agent#87]
I am new to micro-ros and trying to communicate with Rasbperry Pi Pico using micro-ros-agent but when i execute 
`snap interface serial-port`
I see the following output
```
name:    serial-port
summary: allows accessing a specific serial port
plugs:
  - arduino
  - micro-ros-agent
```

and It doesn't show any port. And when i run   `micro-ros-agent serial --dev /dev/ttyACM0 -b 115200` it shows: 
```
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[1626044708.103592] error    | TermiosAgentLinux.cpp | init                     | open device error      | device: /dev/ttyACM0, errno: 13. Please re-run with superuser privileges.
Error while starting serial agent!
Segmentation fault (core dumped)
```

Any suggestion please!

**Comment by pablogs9** [comment]
Currently, the micro-ROS snap package is not working properly, we are working on a solution. Is it possible for you to build the agent from scratch with the setup tool: [micro_ros_setup](https://github.com/micro-ROS/micro_ros_setup)?

**Comment by MuhammadUbuntu** [comment]
@pablogs9  I have already tried [micro_ros_setup ](https://github.com/micro-ROS/micro_ros_setup)and when i run 
`ros2 run micro_ros_setup create_firmware_ws.sh freertos olimex-stm32-e407`
i have gotten some errors.

**Comment by pablogs9** [comment]
Have you run it with `sudo` as the errors message says?

` Please re-run with superuser privileges.`?

**Comment by MuhammadUbuntu** [comment]
I have tried it with `sudo`  and the error message was something like `colcon finished with stlerr.` . After that i have deleted all uros_ws and didn't complete ahead.

**Comment by pablogs9** [comment]
Could you be more specific and paste here your output with sudo in the agent launch?
